#!/bin/bash

echo "[+] Creating cleanup script"
cat << EOF > "$rootfs/cleanup"
#!/bin/bash
rm -fv /root/.bash_history
apt-get clean
rm -fv /var/lib/apt/lists/*
rm -fv /0
rm -fv /hs_err*
rm -fv /third-stage
rm -fv /cleanup
rm -fv /usr/bin/qemu*
EOF

chmod +x "$rootfs/cleanup"
chroot_do /cleanup

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

echo "[+] Completed stage 4!"
