#!/usr/bin/env bash

echo "[+] Creating cleanup script"
cat << EOF > "$rootfs/cleanup"
#!/usr/bin/env sh
rm -fv /root/.bash_history
apt-get clean
rm -fv /var/lib/apt/lists/*
rm -fv /0
rm -fv /hs_err*
rm -fv /third-stage
rm -fv /cleanup
rm -fv /usr/bin/qemu*
EOF

chmod +x "$rootfs/cleanup"
chroot_do /cleanup

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

echo "[+] Resetting /etc/apt/sources.list file"
cat << EOF > "$rootfs/etc/apt/sources.list"
deb http://http.kali.org/kali kali-rolling main contrib non-free non-free-firmware
# For source package access, uncomment the following line
# deb-src http://http.kali.org/kali kali-rolling main contrib non-free non-free-firmware
EOF

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

echo "[+] Completed stage 4!"
